project:
  type: book
  resources:
    - CNAME
    - slides/

book:
  title: "Rust for Clinical Study Reports and Submission"
  author:
    - Author One
    - Author Two
  description: |
    Learn how to prepare tables, listings, and figures for
    clinical study report and submit to regulatory agencies,
    the essential part of clinical trial development.

  output-file: "rustcsr"

  cover-image: "assets/cover.jpg"
  image: "assets/preview.png"
  favicon: "assets/favicon.png"

  site-url: https://rustcsr.org/
  repo-url: https://github.com/nanxstats/rustcsr
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin]
  reader-mode: true

  open-graph:
    image: assets/preview.png
    description: |
      Learn how to prepare tables, listings, and figures for
      clinical study report and submit to regulatory agencies,
      the essential part of clinical trial development.
  twitter-card:
    image: assets/preview.png
    description: |
      Learn how to prepare tables, listings, and figures for
      clinical study report and submit to regulatory agencies,
      the essential part of clinical trial development.
    card-style: summary_large_image

  chapters:
    - index.qmd
    - preface.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo, custom.scss]
    mainfont: "Fira Sans, system-ui, -apple-system, Segoe UI, Roboto, Helvetica Neue, Noto Sans, Liberation Sans, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji"
  pdf:
    documentclass: scrreprt
